---
project: inspec/train-aws:master

rubygems:
  - train-aws

slack:
  notify_channel: inspec-notify

github:
  version_tag_format: "v{{version}}"
  minor_bump_labels:
    - "CI/Bump Minor Version"
  major_bump_labels:
    - "CI/Bump Major Version"

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "CI/Skip Version Bump"
        - "CI/Skip All"
  - bash:.expeditor/update_version.sh:
      only_if:
        - built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "CI/Skip Changelog"
        - "CI/Skip All"
  - built_in:build_gem:
      only_if:
        - built_in:bump_version

promote:
  actions:
    - built_in:rollover_changelog
    - built_in:publish_rubygems
